name: Tests

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  NODE_VERSION: 18

jobs:
  test:
    name: Extension Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: NPM Install
        run: npm ci

      - name: Webpack Build
        run: npm run build

      - name: WebExt Lint
        run: npm run lint:ext:firefox

      - name: WebExt Build
        run: npm run build:ext:firefox
