name: Tests

on:
  push:
    branches: master

env:
  NODE_VERSION: 14

jobs:
  test:
    name: Extension Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: node --version
      - run: npm --version

      - name: NPM Install
        run: npm ci

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Webpack Build
        run: npm run webpack
        env:
          NODE_ENV: production

      - name: Web Ext Lint
        run: npm run lint:ext:firefox

      - name: Web Ext Build
        run: npm run build:ext:firefox
