name: Tests

on:
  push:
    branches: master

env:
  CI: true
  NODE_VERSION: 12

jobs:
  test:
    name: Extension Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: node --version
      - run: npm --version

      - name: NPM Install
        run: npm ci

      - name: Webpack Build
        run: npm run webpack
        env:
          NODE_ENV: production
          
      - name: Web Ext Lint
        run: npm run lint:ext:firefox

      - name: Web Ext Build
        run: npm run build:ext:firefox
